services:
  db:
    container_name: marketplace_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
      - 5433:5433
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - .:/data/var/lib/postgresql/data
